// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"azure-vm-backend/internal/handler"
	"azure-vm-backend/internal/repository"
	"azure-vm-backend/internal/server"
	"azure-vm-backend/internal/service"
	"azure-vm-backend/pkg/app"
	"azure-vm-backend/pkg/jwt"
	"azure-vm-backend/pkg/log"
	"azure-vm-backend/pkg/server/http"
	"azure-vm-backend/pkg/sid"
	"github.com/google/wire"
	"github.com/spf13/viper"
)

// Injectors from wire.go:

func NewWire(viperViper *viper.Viper, logger *log.Logger) (*app.App, func(), error) {
	jwtJWT := jwt.NewJwt(viperViper)
	handlerHandler := handler.NewHandler(logger)
	db := repository.NewDB(viperViper, logger)
	repositoryRepository := repository.NewRepository(logger, db)
	transaction := repository.NewTransaction(repositoryRepository)
	sidSid := sid.NewSid()
	serviceService := service.NewService(transaction, logger, sidSid, jwtJWT)
	userRepository := repository.NewUserRepository(repositoryRepository)
	userService := service.NewUserService(serviceService, userRepository)
	userHandler := handler.NewUserHandler(handlerHandler, userService)
	accountsRepository := repository.NewAccountsRepository(repositoryRepository)
	subscriptionsRepository := repository.NewSubscriptionsRepository(repositoryRepository)
	subscriptionsService := service.NewSubscriptionsService(serviceService, subscriptionsRepository, accountsRepository)
	virtualMachineRepository := repository.NewVirtualMachineRepository(repositoryRepository)
	virtualMachineService := service.NewVirtualMachineService(serviceService, virtualMachineRepository, accountsRepository, subscriptionsRepository, logger)
	accountsService := service.NewAccountsService(serviceService, accountsRepository, subscriptionsService, virtualMachineService)
	accountsHandler := handler.NewAccountsHandler(handlerHandler, accountsService)
	subscriptionsHandler := handler.NewSubscriptionsHandler(handlerHandler, subscriptionsService)
	virtualMachineHandler := handler.NewVirtualMachineHandler(handlerHandler, virtualMachineService)
	vmRegionRepository := repository.NewVmRegionRepository(repositoryRepository)
	vmRegionService := service.NewVmRegionService(serviceService, vmRegionRepository)
	vmRegionHandler := handler.NewVmRegionHandler(handlerHandler, vmRegionService)
	httpServer := server.NewHTTPServer(logger, viperViper, jwtJWT, userHandler, accountsHandler, subscriptionsHandler, virtualMachineHandler, vmRegionHandler)
	job := server.NewJob(logger)
	task := server.NewTask(logger, accountsService)
	appApp := newApp(httpServer, job, task)
	return appApp, func() {
	}, nil
}

// wire.go:

var repositorySet = wire.NewSet(repository.NewDB, repository.NewRepository, repository.NewTransaction, repository.NewUserRepository, repository.NewAccountsRepository, repository.NewSubscriptionsRepository, repository.NewVirtualMachineRepository, repository.NewVmRegionRepository, repository.NewVmImageRepository, repository.NewVmSizeRepository)

var serviceSet = wire.NewSet(service.NewService, service.NewUserService, service.NewAccountsService, service.NewSubscriptionsService, service.NewVirtualMachineService, service.NewVmRegionService, service.NewVmImageService, service.NewVmSizeService)

var handlerSet = wire.NewSet(handler.NewHandler, handler.NewUserHandler, handler.NewAccountsHandler, handler.NewSubscriptionsHandler, handler.NewVirtualMachineHandler, handler.NewVmRegionHandler, handler.NewVmImageHandler, handler.NewVmSizeHandler)

var serverSet = wire.NewSet(server.NewHTTPServer, server.NewJob, server.NewTask)

// build App
func newApp(
	httpServer *http.Server,
	job *server.Job,
	task *server.Task,
) *app.App {
	return app.NewApp(app.WithServer(httpServer, job, task), app.WithName("server"))
}
